
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MealsServiceService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:9999/mealsService?wsdl")
public class MealsServiceService
    extends Service
{

    private final static URL MEALSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MEALSSERVICESERVICE_EXCEPTION;
    private final static QName MEALSSERVICESERVICE_QNAME = new QName("http://server/", "MealsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/mealsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEALSSERVICESERVICE_WSDL_LOCATION = url;
        MEALSSERVICESERVICE_EXCEPTION = e;
    }

    public MealsServiceService() {
        super(__getWsdlLocation(), MEALSSERVICESERVICE_QNAME);
    }

    public MealsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEALSSERVICESERVICE_QNAME, features);
    }

    public MealsServiceService(URL wsdlLocation) {
        super(wsdlLocation, MEALSSERVICESERVICE_QNAME);
    }

    public MealsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEALSSERVICESERVICE_QNAME, features);
    }

    public MealsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MealsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MealsService
     */
    @WebEndpoint(name = "MealsServicePort")
    public MealsService getMealsServicePort() {
        return super.getPort(new QName("http://server/", "MealsServicePort"), MealsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MealsService
     */
    @WebEndpoint(name = "MealsServicePort")
    public MealsService getMealsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "MealsServicePort"), MealsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEALSSERVICESERVICE_EXCEPTION!= null) {
            throw MEALSSERVICESERVICE_EXCEPTION;
        }
        return MEALSSERVICESERVICE_WSDL_LOCATION;
    }

}
