
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MealsService", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MealsService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllItems", targetNamespace = "http://server/", className = "client.GetAllItems")
    @ResponseWrapper(localName = "getAllItemsResponse", targetNamespace = "http://server/", className = "client.GetAllItemsResponse")
    @Action(input = "http://server/MealsService/getAllItemsRequest", output = "http://server/MealsService/getAllItemsResponse")
    public List<String> getAllItems();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://server/", className = "client.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://server/", className = "client.GetItemResponse")
    @Action(input = "http://server/MealsService/getItemRequest", output = "http://server/MealsService/getItemResponse")
    public String getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addItem", targetNamespace = "http://server/", className = "client.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://server/", className = "client.AddItemResponse")
    @Action(input = "http://server/MealsService/addItemRequest", output = "http://server/MealsService/addItemResponse")
    public String addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateItem", targetNamespace = "http://server/", className = "client.UpdateItem")
    @ResponseWrapper(localName = "updateItemResponse", targetNamespace = "http://server/", className = "client.UpdateItemResponse")
    @Action(input = "http://server/MealsService/updateItemRequest", output = "http://server/MealsService/updateItemResponse")
    public String updateItem(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://server/", className = "client.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://server/", className = "client.DeleteItemResponse")
    @Action(input = "http://server/MealsService/deleteItemRequest", output = "http://server/MealsService/deleteItemResponse")
    public String deleteItem(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
